### ISSUE TITLE
Pretraining dataset for natural images

### ISSUE THREAD

**Issue by Huiimin5** [alextamkin/dabs#4]
Hello,

Thank you so much for your contribution. 

It is not clear to me which dataset is actually used for pretraining on natural image domain. In section 4, you claimed that ImageNet is the pretraining dataset. But in the first two tables in the readme file, you mentioned cifar10 is used for pretraining. 
![image](https://user-images.githubusercontent.com/11154631/194737850-184054c4-f363-46d6-b38d-ac603364aab3.png)

Also, in Table 3 of your supplementary, it is specified that cifar10 is used in "both" phases.
![image](https://user-images.githubusercontent.com/11154631/194737831-b5f8c900-1b54-4a3c-84f7-73e2ed3dd531.png)

By the way, the accuracy on downstream datasets does not average to 27.9 as reported in Table 1.
![image](https://user-images.githubusercontent.com/11154631/194738039-ecdd4188-fd1c-4e1e-ab72-5b2b3dc05489.png)
![image](https://user-images.githubusercontent.com/11154631/194738047-c412376b-cbe8-44de-95b2-0246a0bc6505.png)

I am curious about where the difference comes from since you have seeded your training and different runs cannot explain such a variation.

Thank you for your time.

**Comment by alextamkin** [comment]
Thanks! ImageNet is the correct pretraining dataset for the natural images domain, but you are correct that some of those numbers still reflect the CIFAR-10 dataset, which we used initially. We have updated the repo and paper to ensure everything reflects the fact that we are using ImageNet.
