### ISSUE TITLE
Genomics Dataset Transfer Learning

### ISSUE THREAD

**Issue by ChoiDae1** [alextamkin/dabs#5]
In your DABS 2.0 Paper, I confirmed Genomics linear probing result in table1. Is this result in-domain result?(or outdomain) ,
When I saw your code, there are two type for transfer learning in Genomics. (in domain, out domain)

**Comment by alextamkin** [comment]
It's an average of the two!

**Comment by ChoiDae1** [comment]
Thank you for answering!
