### ISSUE TITLE
Error in vocab size for bert-base-uncased

### ISSUE THREAD

**Issue by catalys1** [alextamkin/dabs#6]
Hey! Just wanted to point out a small error I came across.

On this line: https://github.com/alextamkin/dabs/blob/main/src/datasets/text/utils.py#L23
the vocab size is set to 35022, referencing bert-base-uncased. The actual bert-base-uncased vocab size is 30522. It appears to be correct other places in the repo, for instance here: https://github.com/alextamkin/dabs/blob/main/src/datasets/captioned_images/mscoco.py#L33

**Comment by alextamkin** [comment]
Fixed, thanks!
